---
application:
  name: "n8n"
  project: "n8n"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "n8n-db"
  version: "12"
routers:
- name: "main-n8n"
  routes:
  - application_name: "n8n"
    paths:
    - "/*"
