---
application:
  name: "n8n"
  project: "n8n"
  organization: "While and for"
databases:
- type: "POSTGRESQL"
  name: "n8n-db"
  version: "12"
routers:
- name: "main-n8n"
  custom_domains:
  - branch: main
    domain: n8n.pickmee.io
  routes:
  - application_name: "n8n"
    paths:
    - "/*"
